# Builder image
FROM bellsoft/liberica-runtime-container:jre-21.0.6-musl as builder
WORKDIR /workspace
LABEL version="1.0.0"
LABEL email="cadb.craftsman@gmail.com"
COPY maven/target/*.jar application.jar
RUN java -Djarmode=layertools -jar application.jar extract

FROM bellsoft/liberica-runtime-container:jre-21.0.6-musl
WORKDIR /workspace
# Extract dependencies
COPY --from=builder workspace/dependencies/ ./
RUN true
COPY --from=builder workspace/spring-boot-loader/ ./
RUN mkdir -p /workspace/target/data
COPY --from=builder workspace/snapshot-dependencies/ ./
RUN mkdir -p /workspace/target/logs
COPY --from=builder workspace/application/ ./
# Copy self signed certified
#COPY maven/src/main/resources/certs/self_signed.pem /usr/share/ca-certificates/self_signed.pem
#RUN keytool -importcert -cacerts -file /usr/share/ca-certificates/self_signed.pem -cacerts -keypass changeit -storepass changeit -noprompt -alias "*.self_signed"
# Create user and group
RUN addgroup -g 1000 -S spring && adduser -u 1000 -S -D -H spring -G spring
# Change user and group of folder and subfolders 
RUN chown spring -R /workspace && chgrp spring -R /workspace
# Set user
USER spring
ENTRYPOINT ["java", "org.springframework.boot.loader.launch.JarLauncher"]
EXPOSE 8080